version: 2
jobs:
  linux-test:
    docker:
      - image: jadarve/lluvia:22.04
        auth:
          username: jadarve
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: bazel test --test_output=errors //...
      - store_test_results:
        path: bazel-testlogs

workflows:
  version: 2
  linux:
    jobs:
      - linux-test
