version: 2

orbs:
  win: circleci/windows@4.1

jobs:
  linux-test:
    docker:
      - image: jadarve/lluvia:22.04
        auth:
          username: jadarve
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: bazel test --test_output=errors //...
      - store_test_results:
          path: bazel-testlogs
  
  windows-build:
    executor:
      name: win/default
      size: "medium"
    steps:
      - run:
          name: Install tools
          command: |
          choco install --no-progress wget
          choco install --no-progress python2
      - run:
          name: Install Python dependencies
          command: |
          python -m pip install jinja2
          pip3 install cython numpy pytest jinja2 markupsafe
      - run:
          name: Install Vulkan SDK
          command: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.176.1/windows/VulkanSDK-1.2.176.1-Installer.exe" -OutFile VulkanSDK.exe
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
          $installer.WaitForExit();
      - checkout
      - run:
          name: Build
          command: |
          $Env:VULKAN_SDK = "C:/VulkanSDK/1.2.176.1"
          $Env:Path += ";C:/Python27"
          $Env:Path += ";C:/VulkanSDK/1.2.176.1/Bin"
          bazel build //...


workflows:
  version: 2
  linux:
    jobs:
      - linux-test
      - windows-build
