version: 2.1

orbs:
  win: circleci/windows@4.1

jobs:
  # linux-test:
  #   docker:
  #     - image: jadarve/lluvia:22.04
  #       auth:
  #         username: jadarve
  #         password: $DOCKERHUB_PASSWORD
  #   steps:
  #     - checkout
  #     - run: bazel test --test_output=errors //...
  #     - store_test_results:
  #         path: bazel-testlogs
  
  windows-build:
    executor:
      name: win/default
      size: medium
    steps:
      - run:
          name: Install tools
          command: |
            choco install --no-progress wget
            choco install --no-progress python
            choco install --no-progress vulkan-sdk
            choco install --no-progress bazel
            # choco install --no-progress python2
      - run:
          name: Install Python dependencies
          command: |
            # python2 -m pip install jinja2
            python -m pip install cython numpy pytest jinja2 markupsafe
      # - run:
      #     name: Install Vulkan SDK
      #     command: |
      #       Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.176.1/windows/VulkanSDK-1.2.176.1-Installer.exe" -OutFile VulkanSDK.exe
      #       $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
      #       $installer.WaitForExit();
      - checkout:
          path: lluvia
      - run:
          name: Build
          command: |
            cd lluvia
            $Env:VULKAN_SDK = "C:/VulkanSDK/1.2.182.0"
            $Env:Path += ";C:/Python310"
            $Env:Path += ";C:/VulkanSDK/1.2.182.0/Bin"
            bazel build //...


workflows:
  version: 2
  linux:
    jobs:
      # - linux-test
      - windows-build
